trigger:
- master

pool:
  name: 'shared-pool'
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  project: '**/Logger.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: BuildAndTest
  displayName: Build and Test
  steps:
  - task: NuGetCommand@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      restoreSolution: '$(solution)'
      feedsToUse: 'select'
      vstsFeed: '063bfe6a-f1c0-474d-bdb1-e6ef5a17ecbd/cb22b8c5-c32b-4931-b1f0-b60ce3fbd423'
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'build'
      projects: '$(solution)'

- job: CreateNugetPackage
  displayName: Create Nuget Package
  dependsOn: BuildAndTest
  condition: succeeded()
  steps:
  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: 'pack'
      packagesToPack: '$(project)'
      versioningScheme: 'off'
  - task: DotNetCoreCLI@2
    displayName: dotnet push
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '063bfe6a-f1c0-474d-bdb1-e6ef5a17ecbd/cb22b8c5-c32b-4931-b1f0-b60ce3fbd423'
  - task: PublishBuildArtifacts@1
    displayName: publish artifact
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      TargetPath: '\\Logger\$(Build.DefinitionName)\$(Build.BuildNumber)'
      publishLocation: 'Container'